package com.itba.edu.ar.game;

public enum Rule {
    CONWAY_2D_RULE_SET,
    UNRESTRICTED_MULTIPLE_2D_RULE_SET,
    THIRD_2D_RULE_SET,
    PRIME_LESS_40_PRIME_3D_RULE_SET,
    PRIME_BETWEEN_4_AND_20_PRIME_RULE_SET,
    DIFFERENT_MULTIPLES_RULE_SET
}
